# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for tapps-mcp.exe."""

import os
import sys
from pathlib import Path

from PyInstaller.building.api import COLLECT, EXE, PYZ
from PyInstaller.building.build_main import Analysis

block_cipher = None

# Source package directories (monorepo)
pkg_tapps_mcp = Path("packages/tapps-mcp/src/tapps_mcp")
pkg_tapps_mcp_parent = Path("packages/tapps-mcp/src")
pkg_tapps_core = Path("packages/tapps-core/src/tapps_core")
pkg_tapps_core_parent = Path("packages/tapps-core/src")

# Collect ALL data files (knowledge .md, prompts .md, config .yaml, py.typed)
datas = []

for root, dirs, files in os.walk(str(pkg_tapps_mcp)):
    for f in files:
        if f.endswith((".md", ".yaml", ".yml", ".typed")):
            full = os.path.join(root, f)
            rel_dir = os.path.relpath(root, str(pkg_tapps_mcp_parent))
            datas.append((full, rel_dir))

for root, dirs, files in os.walk(str(pkg_tapps_core)):
    for f in files:
        if f.endswith((".md", ".yaml", ".yml", ".typed")):
            full = os.path.join(root, f)
            rel_dir = os.path.relpath(root, str(pkg_tapps_core_parent))
            datas.append((full, rel_dir))

a = Analysis(
    ["scripts/run_tapps_mcp.py"],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=[
        "tapps_mcp",
        "tapps_mcp.cli",
        "tapps_mcp.server",
        "tapps_mcp.server_helpers",
        "tapps_mcp.server_scoring_tools",
        "tapps_mcp.server_pipeline_tools",
        "tapps_mcp.server_metrics_tools",
        "tapps_mcp.server_memory_tools",
        "tapps_mcp.server_analysis_tools",
        "tapps_mcp.server_resources",
        "tapps_mcp.server_linear_tools",
        "tapps_mcp.server_release_tools",
        "tapps_mcp.diagnostics",
        "tapps_mcp.common",
        "tapps_mcp.common.exceptions",
        "tapps_mcp.common.logging",
        "tapps_mcp.common.models",
        "tapps_mcp.common.nudges",
        "tapps_mcp.common.output_schemas",
        "tapps_mcp.common.elicitation",
        "tapps_mcp.common.constants",
        "tapps_mcp.common.developer_workflow",
        "tapps_mcp.common.pipeline_models",
        "tapps_mcp.common.utils",
        "tapps_mcp.config",
        "tapps_mcp.config.settings",
        "tapps_mcp.security",
        "tapps_mcp.security.path_validator",
        "tapps_mcp.security.io_guardrails",
        "tapps_mcp.security.governance",
        "tapps_mcp.security.api_keys",
        "tapps_mcp.security.secret_scanner",
        "tapps_mcp.security.content_safety",
        "tapps_mcp.security.security_scanner",
        "tapps_mcp.security.domain_patterns",
        "tapps_mcp.scoring",
        "tapps_mcp.scoring.cross_ref",
        "tapps_mcp.scoring.language_detector",
        "tapps_mcp.scoring.models",
        "tapps_mcp.scoring.constants",
        "tapps_mcp.scoring.scorer",
        "tapps_mcp.scoring.scorer_base",
        "tapps_mcp.scoring.scorer_go",
        "tapps_mcp.scoring.scorer_rust",
        "tapps_mcp.scoring.scorer_typescript",
        "tapps_mcp.scoring.suggestions",
        "tapps_mcp.scoring.dead_code",
        "tapps_mcp.scoring.dependency_security",
        "tapps_mcp.gates",
        "tapps_mcp.gates.models",
        "tapps_mcp.gates.evaluator",
        "tapps_mcp.tools",
        "tapps_mcp.tools.subprocess_utils",
        "tapps_mcp.tools.subprocess_runner",
        "tapps_mcp.tools.tool_detection",
        "tapps_mcp.tools.ruff",
        "tapps_mcp.tools.ruff_direct",
        "tapps_mcp.tools.mypy",
        "tapps_mcp.tools.bandit",
        "tapps_mcp.tools.radon",
        "tapps_mcp.tools.radon_direct",
        "tapps_mcp.tools.parallel",
        "tapps_mcp.tools.checklist",
        "tapps_mcp.tools.checklist_policy",
        "tapps_mcp.tools.insight_recall",
        "tapps_mcp.tools.batch_validator",
        "tapps_mcp.tools.vulture",
        "tapps_mcp.tools.pip_audit",
        "tapps_mcp.tools.dependency_scan_cache",
        "tapps_mcp.tools.content_hash_cache",
        "tapps_mcp.tools.perflint",
        "tapps_mcp.tools.validate_changed",
        "tapps_mcp.tools.validate_changed_output",
        "tapps_mcp.tools.validation_progress",
        "tapps_mcp.tools.session_start_helpers",
        "tapps_mcp.tools.session_start_core",
        "tapps_mcp.tools.decompose_helpers",
        "tapps_mcp.tools.pipeline_init_helpers",
        "tapps_mcp.tools.pipeline_orchestrator",
        "tapps_mcp.tools.engagement_level",
        "tapps_mcp.tools.loop_metrics",
        "tapps_mcp.tools.release_update",
        "tapps_mcp.knowledge",
        "tapps_mcp.knowledge.models",
        "tapps_mcp.knowledge.cache",
        "tapps_mcp.knowledge.fuzzy_matcher",
        "tapps_mcp.knowledge.context7_client",
        "tapps_mcp.knowledge.rag_safety",
        "tapps_mcp.knowledge.lookup",
        "tapps_mcp.knowledge.circuit_breaker",
        "tapps_mcp.knowledge.library_detector",
        "tapps_mcp.knowledge.warming",
        "tapps_mcp.knowledge.import_analyzer",
        "tapps_mcp.knowledge.content_normalizer",
        "tapps_mcp.knowledge.providers",
        "tapps_mcp.knowledge.providers.base",
        "tapps_mcp.knowledge.providers.registry",
        "tapps_mcp.knowledge.providers.context7_provider",
        "tapps_mcp.knowledge.providers.llms_txt_provider",
        "tapps_mcp.validators",
        "tapps_mcp.validators.base",
        "tapps_mcp.validators.mcp_config",
        "tapps_mcp.validators.dockerfile",
        "tapps_mcp.validators.docker_compose",
        "tapps_mcp.validators.websocket",
        "tapps_mcp.validators.mqtt",
        "tapps_mcp.validators.influxdb",
        # Expert modules removed EPIC94
        "tapps_mcp.project",
        "tapps_mcp.project.models",
        "tapps_mcp.project.ast_parser",
        "tapps_mcp.project.tech_stack",
        "tapps_mcp.project.type_detector",
        "tapps_mcp.project.profiler",
        "tapps_mcp.project.session_notes",
        "tapps_mcp.project.impact_analyzer",
        "tapps_mcp.project.report",
        "tapps_mcp.project.import_graph",
        "tapps_mcp.project.cycle_detector",
        "tapps_mcp.project.coupling_metrics",
        "tapps_mcp.project.vulnerability_impact",
        "tapps_mcp.adaptive",
        "tapps_mcp.adaptive.models",
        "tapps_mcp.adaptive.protocols",
        "tapps_mcp.adaptive.persistence",
        "tapps_mcp.adaptive.scoring_engine",
        "tapps_mcp.adaptive.scoring_wrapper",
        "tapps_mcp.adaptive.voting_engine",
        "tapps_mcp.adaptive.weight_distributor",
        "tapps_mcp.metrics",
        "tapps_mcp.metrics.collector",
        "tapps_mcp.metrics.execution_metrics",
        "tapps_mcp.metrics.outcome_tracker",
        # expert_metrics removed
        "tapps_mcp.metrics.confidence_metrics",
        "tapps_mcp.metrics.rag_metrics",
        "tapps_mcp.metrics.consultation_logger",
        # expert_observability + business_metrics removed
        "tapps_mcp.metrics.quality_aggregator",
        "tapps_mcp.metrics.alerts",
        "tapps_mcp.metrics.trends",
        "tapps_mcp.metrics.visualizer",
        "tapps_mcp.metrics.dashboard",
        "tapps_mcp.metrics.otel_export",
        "tapps_mcp.metrics.feedback",
        "tapps_mcp.quick_check_recurring",
        "tapps_mcp.prompts",
        "tapps_mcp.prompts.prompt_loader",
        "tapps_mcp.distribution",
        "tapps_mcp.distribution.setup_generator",
        "tapps_mcp.distribution.doctor",
        "tapps_mcp.distribution.exe_manager",
        "tapps_mcp.distribution.plugin_builder",
        "tapps_mcp.distribution.rollback",
        "tapps_mcp.pipeline",
        "tapps_mcp.pipeline.models",
        # persona_resolver removed
        "tapps_mcp.pipeline.skills_validator",
        "tapps_mcp.pipeline.handoff",
        "tapps_mcp.pipeline.init",
        "tapps_mcp.pipeline.upgrade",
        "tapps_mcp.pipeline.agents_md",
        "tapps_mcp.pipeline.karpathy_block",
        "tapps_mcp.pipeline.github_templates",
        "tapps_mcp.pipeline.ci_install",
        "tapps_mcp.pipeline.github_ci",
        "tapps_mcp.pipeline.github_copilot",
        "tapps_mcp.pipeline.github_governance",
        "tapps_mcp.pipeline.platform_generators",
        "tapps_mcp.pipeline.platform_hooks",
        "tapps_mcp.pipeline.platform_rules",
        "tapps_mcp.pipeline.platform_bundles",
        "tapps_mcp.pipeline.platform_hook_templates",
        "tapps_mcp.pipeline.platform_skills",
        "tapps_mcp.pipeline.platform_subagents",
        "tapps_mcp.pipeline.platform_docs_automation",
        "tapps_mcp.pipeline.migrate_memory",
        "tapps_mcp.pipeline.git_hooks",
        "tapps_mcp.pipeline.tapps_obligations_block",
        "tapps_mcp.pipeline.linear_sdlc",
        "tapps_mcp.pipeline.linear_sdlc.config",
        "tapps_mcp.pipeline.linear_sdlc.renderer",
        "tapps_mcp.pipeline.linear_sdlc.installer",
        "tapps_mcp.platform",
        "tapps_mcp.platform.cli",
        "tapps_mcp.platform.combined_server",
        "tapps_mcp.memory",
        "tapps_mcp.memory.auto_capture",
        "tapps_mcp.memory.models",
        "tapps_mcp.memory.persistence",
        "tapps_mcp.memory.store",
        "tapps_mcp.memory.decay",
        "tapps_mcp.memory.reinforcement",
        "tapps_mcp.memory.contradictions",
        "tapps_mcp.memory.gc",
        "tapps_mcp.memory.retrieval",
        "tapps_mcp.memory.injection",
        "tapps_mcp.memory.seeding",
        "tapps_mcp.memory.io",
        "tapps_mcp.benchmark",
        "tapps_mcp.benchmark.ablation",
        "tapps_mcp.benchmark.adaptive_feedback",
        "tapps_mcp.benchmark.analyzer",
        "tapps_mcp.benchmark.call_patterns",
        "tapps_mcp.benchmark.checklist_calibrator",
        "tapps_mcp.benchmark.cli_commands",
        "tapps_mcp.benchmark.config",
        "tapps_mcp.benchmark.context_injector",
        "tapps_mcp.benchmark.dataset",
        "tapps_mcp.benchmark.docker_runner",
        "tapps_mcp.benchmark.engagement_calibrator",
        "tapps_mcp.benchmark.evaluator",
        # expert_tracker removed
        "tapps_mcp.benchmark.failure_analyzer",
        "tapps_mcp.benchmark.memory_tracker",
        "tapps_mcp.benchmark.mock_evaluator",
        "tapps_mcp.benchmark.models",
        "tapps_mcp.benchmark.promotion",
        "tapps_mcp.benchmark.redundancy",
        "tapps_mcp.benchmark.reporter",
        "tapps_mcp.benchmark.template_versions",
        "tapps_mcp.benchmark.insight_benchmark",
        "tapps_mcp.benchmark.tool_evaluator",
        "tapps_mcp.benchmark.tool_report",
        "tapps_mcp.benchmark.tool_task_models",
        # Third-party hidden imports
        "click",
        "pydantic",
        "pydantic_settings",
        "structlog",
        "yaml",
        "anyio",
        "httpx",
        "filelock",
        "mcp",
        "mcp.server",
        "mcp.server.fastmcp",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude optional heavy deps that aren't needed for core functionality
        "faiss",
        "sentence_transformers",
        "numpy",
        "torch",
        "transformers",
        # Exclude dev deps
        "pytest",
        "mypy",
        "ruff",
        "pre_commit",
        "playwright",
    ],
    noarchive=False,
    optimize=0,
    cipher=block_cipher,
)

pyz = PYZ(a.pure, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="tapps-mcp",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
