"""Tests for scripts/gen_sprint_board.py — the SPRINT_BOARD.md generator.

docs/SPRINT_BOARD.md is generated from Linear, not hand-maintained (the
prior hand-maintained docs/TAPPS_BACKLOG_PLAN.md drifted for the same
reason). These tests cover the render/grouping/freshness logic directly;
scripts/gen-sprint-board.py is a thin CLI shim over this module.
"""

from __future__ import annotations

import importlib
import json
import sys
from datetime import date, timedelta
from pathlib import Path
from typing import TYPE_CHECKING

import pytest

if TYPE_CHECKING:
    from types import ModuleType

REPO_ROOT = Path(__file__).resolve().parents[4]
SCRIPTS_DIR = REPO_ROOT / "scripts"


@pytest.fixture
def gsb() -> ModuleType:
    """Import scripts/gen_sprint_board.py — scripts/ is not an installed package."""
    if str(SCRIPTS_DIR) not in sys.path:
        sys.path.insert(0, str(SCRIPTS_DIR))
    return importlib.reload(importlib.import_module("gen_sprint_board"))


def _raw_issue(
    issue_id: str,
    priority: str,
    *,
    status: str = "Backlog",
    parent_id: str | None = None,
    url: str | None = None,
) -> dict[str, object]:
    return {
        "id": issue_id,
        "title": f"Title for {issue_id}",
        "priority": {"name": priority},
        "status": status,
        "statusType": status.lower(),
        "parentId": parent_id,
        "url": url or f"https://linear.app/example/issue/{issue_id}",
    }


class TestIssueFromDict:
    def test_from_dict_maps_priority_name(self, gsb: ModuleType) -> None:
        issue = gsb.Issue.from_dict(_raw_issue("TAP-1", "High"))
        assert issue.priority == "High"
        assert issue.id == "TAP-1"

    def test_from_dict_defaults_missing_priority(self, gsb: ModuleType) -> None:
        raw = _raw_issue("TAP-2", "High")
        raw["priority"] = None
        issue = gsb.Issue.from_dict(raw)
        assert issue.priority == "No priority"

    def test_from_dict_missing_parent_id_is_none(self, gsb: ModuleType) -> None:
        raw = _raw_issue("TAP-3", "Low")
        del raw["parentId"]
        issue = gsb.Issue.from_dict(raw)
        assert issue.parent_id is None


class TestPriorityCounts:
    def test_counts_summary_orders_by_severity_and_skips_zero(self, gsb: ModuleType) -> None:
        issues = [
            gsb.Issue.from_dict(_raw_issue("TAP-1", "Medium")),
            gsb.Issue.from_dict(_raw_issue("TAP-2", "Urgent")),
            gsb.Issue.from_dict(_raw_issue("TAP-3", "Medium")),
        ]
        assert gsb._counts_summary(issues) == "3 open (1 Urgent, 2 Medium)"


class TestRender:
    def test_render_groups_priorities_urgent_to_low(self, gsb: ModuleType) -> None:
        issues = [
            gsb.Issue.from_dict(_raw_issue("TAP-2", "Low")),
            gsb.Issue.from_dict(_raw_issue("TAP-1", "Urgent")),
            gsb.Issue.from_dict(_raw_issue("TAP-3", "High")),
        ]
        content = gsb.render(issues, date(2026, 1, 1))
        urgent_pos = content.index("## Urgent")
        high_pos = content.index("## High")
        low_pos = content.index("## Low")
        assert urgent_pos < high_pos < low_pos
        assert "TAP-1" in content and "TAP-3" in content and "TAP-2" in content

    def test_render_nests_children_under_parent(self, gsb: ModuleType) -> None:
        issues = [
            gsb.Issue.from_dict(_raw_issue("TAP-100", "High")),
            gsb.Issue.from_dict(_raw_issue("TAP-101", "High", parent_id="TAP-100")),
        ]
        content = gsb.render(issues, date(2026, 1, 1))
        parent_pos = content.index("TAP-100")
        child_line = next(line for line in content.splitlines() if "TAP-101" in line)
        assert content.index("TAP-101") > parent_pos
        assert child_line.startswith("  -")

    def test_render_treats_orphaned_parent_id_as_top_level(self, gsb: ModuleType) -> None:
        issues = [gsb.Issue.from_dict(_raw_issue("TAP-5", "Medium", parent_id="TAP-999"))]
        content = gsb.render(issues, date(2026, 1, 1))
        line = next(line for line in content.splitlines() if "TAP-5" in line)
        assert line.startswith("- [TAP-5]")

    def test_render_header_carries_generated_date_and_counts(self, gsb: ModuleType) -> None:
        issues = [gsb.Issue.from_dict(_raw_issue("TAP-1", "High"))]
        content = gsb.render(issues, date(2026, 3, 4))
        assert "Generated: 2026-03-04" in content
        assert "1 open (1 High)" in content
        assert "GENERATED by scripts/gen-sprint-board.py — do not hand-edit." in content


class TestLoadIssues:
    def test_load_issues_reads_snapshot_file(self, gsb: ModuleType, tmp_path: Path) -> None:
        snapshot = {
            "generated_from": "Linear",
            "generated_at": "2026-01-01",
            "issues": [_raw_issue("TAP-1", "Urgent")],
        }
        path = tmp_path / "snapshot.json"
        path.write_text(json.dumps(snapshot), encoding="utf-8")
        issues = gsb.load_issues(path)
        assert len(issues) == 1
        assert issues[0].id == "TAP-1"


class TestFindDefaultInput:
    def test_raises_when_snapshot_dir_missing(self, gsb: ModuleType, tmp_path: Path) -> None:
        gsb.SNAPSHOT_DIR = tmp_path / "does-not-exist"
        with pytest.raises(FileNotFoundError, match="snapshot dir does not exist"):
            gsb.find_default_input()

    def test_raises_when_snapshot_dir_empty(self, gsb: ModuleType, tmp_path: Path) -> None:
        gsb.SNAPSHOT_DIR = tmp_path
        with pytest.raises(FileNotFoundError, match="no snapshot files found"):
            gsb.find_default_input()

    def test_returns_newest_snapshot_file(self, gsb: ModuleType, tmp_path: Path) -> None:
        gsb.SNAPSHOT_DIR = tmp_path
        older = tmp_path / "older.json"
        newer = tmp_path / "newer.json"
        older.write_text("{}", encoding="utf-8")
        newer.write_text("{}", encoding="utf-8")
        import os
        import time

        time.sleep(0.01)
        newer.touch()
        os.utime(newer, None)
        assert gsb.find_default_input() == newer


class TestFreshnessCheck:
    def test_is_fresh_ignores_generated_date_line(self, gsb: ModuleType) -> None:
        issues = [gsb.Issue.from_dict(_raw_issue("TAP-1", "High"))]
        today_content = gsb.render(issues, date(2026, 6, 1))
        yesterday_content = gsb.render(issues, date(2026, 5, 31))
        assert gsb.is_fresh(today_content, yesterday_content)

    def test_is_fresh_detects_real_content_drift(self, gsb: ModuleType) -> None:
        base = [gsb.Issue.from_dict(_raw_issue("TAP-1", "High"))]
        drifted = [
            gsb.Issue.from_dict(_raw_issue("TAP-1", "High")),
            gsb.Issue.from_dict(_raw_issue("TAP-2", "Low")),
        ]
        base_content = gsb.render(base, date(2026, 6, 1))
        drifted_content = gsb.render(drifted, date(2026, 6, 1))
        assert not gsb.is_fresh(drifted_content, base_content)


class TestStampFreshness:
    """The CI freshness gate: a board stamp older than 30 days must fail (Sub-goal 2)."""

    def test_fresh_stamp_passes(self, gsb: ModuleType) -> None:
        issues = [gsb.Issue.from_dict(_raw_issue("TAP-1", "High"))]
        content = gsb.render(issues, date(2026, 6, 1))
        assert gsb.is_stamp_fresh(content, today=date(2026, 6, 1)) is True
        assert gsb.stamp_age_days(content, today=date(2026, 6, 1)) == 0

    def test_stamp_exactly_at_threshold_passes(self, gsb: ModuleType) -> None:
        issues = [gsb.Issue.from_dict(_raw_issue("TAP-1", "High"))]
        content = gsb.render(issues, date(2026, 1, 1))
        today = date(2026, 1, 1) + timedelta(days=gsb.MAX_STAMP_AGE_DAYS)
        assert gsb.is_stamp_fresh(content, today=today) is True

    def test_31_day_old_stamp_fails(self, gsb: ModuleType) -> None:
        issues = [gsb.Issue.from_dict(_raw_issue("TAP-1", "High"))]
        content = gsb.render(issues, date(2026, 1, 1))
        today = date(2026, 1, 1) + timedelta(days=gsb.MAX_STAMP_AGE_DAYS + 1)
        assert gsb.stamp_age_days(content, today=today) == gsb.MAX_STAMP_AGE_DAYS + 1
        assert gsb.is_stamp_fresh(content, today=today) is False

    def test_missing_stamp_raises(self, gsb: ModuleType) -> None:
        with pytest.raises(ValueError, match="no 'Generated: YYYY-MM-DD' stamp"):
            gsb.parse_generated_date("# no stamp here\n")
