"""Helper functions for DocsMCP server — response builders and singleton caches."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pathlib import Path

    from docs_mcp.config.settings import DocsMCPSettings


# ---------------------------------------------------------------------------
# Settings singleton — avoids re-loading on every tool call.
# ---------------------------------------------------------------------------

_settings: DocsMCPSettings | None = None


def _get_settings() -> DocsMCPSettings:
    """Return a lazily-initialized :class:`DocsMCPSettings` singleton."""
    global _settings  # noqa: PLW0603
    if _settings is None:
        from docs_mcp.config.settings import load_docs_settings

        _settings = load_docs_settings()
    return _settings


def _reset_settings_cache() -> None:
    """Reset the cached :class:`DocsMCPSettings` singleton (for testing)."""
    global _settings  # noqa: PLW0603
    _settings = None


# ---------------------------------------------------------------------------
# Response builders
# ---------------------------------------------------------------------------


def error_response(tool_name: str, code: str, message: str) -> dict[str, Any]:
    """Build a standard error response envelope."""
    return {
        "tool": tool_name,
        "success": False,
        "elapsed_ms": 0,
        "error": {"code": code, "message": message},
    }


_SENTINEL = object()


def success_response(
    tool_name: str,
    elapsed_ms: int,
    data: dict[str, Any],
    *,
    degraded: bool | object = _SENTINEL,
    next_steps: list[str] | None = None,
) -> dict[str, Any]:
    """Build a standard success response envelope.

    When *degraded* is explicitly passed (even as False), the key is included
    in the response.  When omitted, the key is absent.

    When *next_steps* is non-empty, it is included in ``data`` so the LLM
    sees actionable guidance.
    """
    if next_steps:
        data["next_steps"] = next_steps

    result: dict[str, Any] = {
        "tool": tool_name,
        "success": True,
        "elapsed_ms": elapsed_ms,
        "data": data,
    }
    if degraded is not _SENTINEL:
        result["degraded"] = degraded
    return result


# ---------------------------------------------------------------------------
# Content-return mode helpers (Epic 87)
# ---------------------------------------------------------------------------


def can_write_to_project(root: Path) -> bool:
    """Whether generators should write files directly.

    Returns ``False`` in content-return mode (Docker / read-only filesystem),
    meaning generators should skip file writes and let the AI client apply
    the content from the response.
    """
    from tapps_core.common.file_operations import WriteMode, detect_write_mode

    return detect_write_mode(root) == WriteMode.DIRECT_WRITE


def build_generator_manifest(
    tool_name: str,
    content: str,
    output_path: str,
    *,
    description: str = "",
) -> dict[str, Any]:
    """Build a ``file_manifest`` dict for a generator in content-return mode.

    Generators embed this in their ``data`` dict so the AI client knows
    exactly where and how to write the file.
    """
    from tapps_core.common.file_operations import (
        AgentInstructions,
        FileManifest,
        FileOperation,
    )

    # Tool-specific personas
    personas: dict[str, str] = {
        "docs_generate_readme": "Technical writer creating project README.",
        "docs_generate_changelog": "Release manager updating changelog.",
        "docs_generate_release_notes": "Release manager preparing release notes.",
        "docs_generate_api": "API documentation specialist.",
        "docs_generate_adr": "Architecture decision recorder.",
        "docs_generate_onboarding": "Onboarding guide author.",
        "docs_generate_contributing": "Contributing guide author.",
        "docs_generate_prd": "Product requirements author.",
        "docs_generate_diagram": "Diagram generator.",
        "docs_generate_architecture": "Architecture documentation specialist.",
        "docs_generate_epic": "Project planning specialist creating epics.",
        "docs_generate_story": "Project planning specialist creating stories.",
        "docs_generate_prompt": "Prompt template author.",
    }
    persona = personas.get(
        tool_name,
        "Documentation generator writing files for the project.",
    )

    manifest = FileManifest(
        summary=f"{tool_name}: 1 file to write",
        source_version=_get_docsmcp_version(),
        files=[
            FileOperation(
                path=output_path,
                content=content,
                mode="create",
                description=description or f"Generated by {tool_name}.",
                priority=5,
            ),
        ],
        agent_instructions=AgentInstructions(
            persona=(
                f"You are a {persona}  Write the file exactly as "
                "provided — do not modify content, add comments, or reformat."
            ),
            tool_preference=(
                "Use the Write tool to create the file.  "
                "Create parent directories as needed."
            ),
            verification_steps=[
                f"Verify the file was written to {output_path}.",
                "Run 'git status' to show the user what changed.",
            ],
            warnings=[],
        ),
    )
    return manifest.to_full_response_data()


def _get_docsmcp_version() -> str:
    """Return DocsMCP version string."""
    try:
        from docs_mcp import __version__

        return __version__
    except (ImportError, AttributeError):
        return "unknown"
