"""Integration tests for generator -> validator flow.

Tests that docs generated by DocsMCP generators pass validation checks.
These exercise real code paths without mocking.
"""

from __future__ import annotations

from pathlib import Path

import pytest

pytestmark = [pytest.mark.integration, pytest.mark.slow]


class TestGeneratorValidatorFlow:
    """Test that generated docs pass validation."""

    @pytest.mark.asyncio
    async def test_generated_readme_passes_completeness(self, sample_project: Path) -> None:
        """README generated for a project should improve completeness score."""
        # Import server first to avoid circular import, then access sub-modules
        import docs_mcp.server  # noqa: F401 - triggers full module registration
        from docs_mcp.server_gen_tools import docs_generate_readme
        from docs_mcp.server_val_tools import docs_check_completeness

        # Check completeness before generation
        before = await docs_check_completeness(project_root=str(sample_project))
        assert before["success"] is True

        # Generate a README
        gen_result = await docs_generate_readme(
            style="standard",
            merge=False,
            project_root=str(sample_project),
        )
        assert gen_result["success"] is True

        # Write the generated content so completeness can detect it
        readme_content = gen_result["data"].get("content", "")
        if readme_content:
            (sample_project / "README.md").write_text(readme_content, encoding="utf-8")

        # Check completeness after generation
        after = await docs_check_completeness(project_root=str(sample_project))
        assert after["success"] is True

        # Score should be at least as good (README already existed in sample_project)
        assert after["data"]["overall_score"] >= before["data"]["overall_score"]

    @pytest.mark.asyncio
    async def test_project_scan_then_completeness(self, docs_project: Path) -> None:
        """Project scan and completeness check agree on documentation state."""
        from docs_mcp.server import docs_project_scan
        from docs_mcp.server_val_tools import docs_check_completeness

        scan = await docs_project_scan(project_root=str(docs_project))
        assert scan["success"] is True

        completeness = await docs_check_completeness(project_root=str(docs_project))
        assert completeness["success"] is True

        # Both should report a non-zero score for the well-documented project
        assert scan["data"]["completeness_score"] > 0
        assert completeness["data"]["overall_score"] > 0

    @pytest.mark.asyncio
    async def test_module_map_for_real_python_project(self, sample_project: Path) -> None:
        """Module map should find Python files in a real project structure."""
        from docs_mcp.server_analysis import docs_module_map

        result = await docs_module_map(project_root=str(sample_project))
        assert result["success"] is True

        data = result["data"]
        assert data["total_modules"] >= 1  # At least main.py

    @pytest.mark.asyncio
    async def test_session_start_then_scan_consistency(self, sample_project: Path) -> None:
        """Session start and project scan produce consistent project info."""
        from docs_mcp.server import docs_project_scan, docs_session_start

        session = await docs_session_start(project_root=str(sample_project))
        assert session["success"] is True

        scan = await docs_project_scan(project_root=str(sample_project))
        assert scan["success"] is True

        # Both should identify the same project
        assert session["data"]["project_name"] == "test-project"

    @pytest.mark.asyncio
    async def test_freshness_check_on_real_docs(self, docs_project: Path) -> None:
        """Freshness check should classify existing docs without errors."""
        from docs_mcp.server_val_tools import docs_check_freshness

        result = await docs_check_freshness(project_root=str(docs_project))
        assert result["success"] is True
        assert result["tool"] == "docs_check_freshness"

    @pytest.mark.asyncio
    async def test_generate_changelog_for_non_git_project(self, sample_project: Path) -> None:
        """Changelog generation should handle projects without real git history gracefully."""
        from docs_mcp.server_gen_tools import docs_generate_changelog

        result = await docs_generate_changelog(project_root=str(sample_project))

        # May succeed with empty changelog or fail gracefully
        # The key assertion is that it does not crash
        assert isinstance(result, dict)
        assert "success" in result
