"""Enhanced GitHub Actions CI workflow generators.

Epic 20: Modernize the existing ``tapps-quality.yml`` CI workflow and add
new workflows: CodeQL scanning, Copilot coding agent environment setup,
Dependabot auto-merge, and reusable workflow modules.

Uses SHA-pinned actions, Artifacts v4, minimal permissions, concurrency
groups, and Arm64 runner support where applicable.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pathlib import Path


# ---------------------------------------------------------------------------
# Enhanced Quality Workflow (replaces the basic tapps-quality.yml)
# ---------------------------------------------------------------------------

_QUALITY_WORKFLOW = """\
# .github/workflows/tapps-quality.yml
# Generated by TappsMCP tapps_init — edit as needed
name: TappsMCP Quality Gate

on:
  pull_request:
    paths:
      - "**.py"
  workflow_dispatch:
    inputs:
      preset:
        description: "Quality preset (standard, strict, framework)"
        required: false
        default: "staging"
        type: choice
        options:
          - standard
          - strict
          - framework

permissions:
  contents: read

concurrency:
  group: tapps-quality-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install TappsMCP and checkers
        run: |
          pip install tapps-mcp
          pip install ruff mypy bandit radon vulture

      - name: Run TappsMCP quality gate
        env:
          TAPPS_MCP_PROJECT_ROOT: ${{ github.workspace }}
        run: |
          tapps-mcp validate-changed \\
            --preset ${{ inputs.preset || 'staging' }}

      - name: Upload quality report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tapps-quality-report
          path: .tapps-mcp/reports/
          retention-days: 30
          if-no-files-found: ignore
"""

# ---------------------------------------------------------------------------
# CodeQL Scanning Workflow
# ---------------------------------------------------------------------------

_CODEQL_WORKFLOW = """\
# .github/workflows/codeql-analysis.yml
# Generated by TappsMCP tapps_init — edit as needed
name: CodeQL Analysis

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "30 6 * * 1"  # Monday 6:30 UTC

permissions:
  security-events: write
  contents: read

concurrency:
  group: codeql-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        language: [python]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: +security-extended

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"
"""

# ---------------------------------------------------------------------------
# Copilot Setup Steps Workflow
# ---------------------------------------------------------------------------

_COPILOT_SETUP_STEPS = """\
# .github/workflows/copilot-setup-steps.yml
# Generated by TappsMCP tapps_init
# This workflow configures the environment for the Copilot coding agent.
# See: https://docs.github.com/en/copilot/using-github-copilot/using-copilot-coding-agent
name: Copilot Setup Steps

on: workflow_dispatch

permissions:
  contents: read

jobs:
  copilot-setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install project dependencies
        run: |
          pip install uv
          uv sync --frozen 2>/dev/null || pip install -e ".[dev]" 2>/dev/null || pip install -e . 2>/dev/null || true

      - name: Install quality checkers
        run: |
          pip install tapps-mcp ruff mypy bandit radon vulture pip-audit

      - name: Verify tools
        run: |
          echo "--- TappsMCP ---"
          tapps-mcp doctor 2>/dev/null || echo "tapps-mcp doctor not available"
          echo "--- Ruff ---"
          ruff version
          echo "--- Mypy ---"
          mypy --version
          echo "--- Bandit ---"
          bandit --version
"""

# ---------------------------------------------------------------------------
# Dependabot Auto-Merge Workflow
# ---------------------------------------------------------------------------

_DEPENDABOT_AUTO_MERGE = """\
# .github/workflows/dependabot-auto-merge.yml
# Generated by TappsMCP tapps_init — edit as needed
# Auto-approves and auto-merges Dependabot PRs for minor/patch updates.
name: Dependabot Auto-Merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-approve patch and minor updates
        if: >-
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge patch and minor updates
        if: >-
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
"""

# ---------------------------------------------------------------------------
# Reusable Quality Workflow Module
# ---------------------------------------------------------------------------

_REUSABLE_QUALITY_WORKFLOW = """\
# .github/workflows/tapps-quality-reusable.yml
# Generated by TappsMCP tapps_init — reusable workflow module
# Other workflows can call this via workflow_call.
name: TappsMCP Quality (Reusable)

on:
  workflow_call:
    inputs:
      preset:
        description: "Quality preset"
        required: false
        default: "standard"
        type: string
      python-version:
        description: "Python version"
        required: false
        default: "3.12"
        type: string

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install TappsMCP and checkers
        run: |
          pip install tapps-mcp
          pip install ruff mypy bandit radon vulture

      - name: Run quality gate
        env:
          TAPPS_MCP_PROJECT_ROOT: ${{ github.workspace }}
        run: |
          tapps-mcp validate-changed \\
            --preset ${{ inputs.preset }}
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_enhanced_ci_workflow(project_root: Path) -> dict[str, Any]:
    """Generate enhanced ``.github/workflows/tapps-quality.yml``.

    Replaces the basic workflow with one that includes Artifacts v4,
    permissions, concurrency, and ``workflow_dispatch`` support.

    Returns a summary dict with ``file`` and ``action``.
    """
    wf_dir = project_root / ".github" / "workflows"
    wf_dir.mkdir(parents=True, exist_ok=True)
    target = wf_dir / "tapps-quality.yml"
    existed = target.exists()
    target.write_text(_QUALITY_WORKFLOW, encoding="utf-8")
    return {
        "file": str(target.relative_to(project_root)),
        "action": "updated" if existed else "created",
    }


def generate_codeql_workflow(project_root: Path) -> dict[str, Any]:
    """Generate ``.github/workflows/codeql-analysis.yml``.

    Returns a summary dict with ``file`` and ``action``.
    """
    wf_dir = project_root / ".github" / "workflows"
    wf_dir.mkdir(parents=True, exist_ok=True)
    target = wf_dir / "codeql-analysis.yml"
    target.write_text(_CODEQL_WORKFLOW, encoding="utf-8")
    return {"file": str(target.relative_to(project_root)), "action": "created"}


def generate_copilot_setup_steps(project_root: Path) -> dict[str, Any]:
    """Generate ``.github/workflows/copilot-setup-steps.yml``.

    Configures the Copilot coding agent environment with Python,
    quality checkers, and TappsMCP installed.

    Returns a summary dict with ``file`` and ``action``.
    """
    wf_dir = project_root / ".github" / "workflows"
    wf_dir.mkdir(parents=True, exist_ok=True)
    target = wf_dir / "copilot-setup-steps.yml"
    target.write_text(_COPILOT_SETUP_STEPS, encoding="utf-8")
    return {"file": str(target.relative_to(project_root)), "action": "created"}


def generate_dependabot_auto_merge(project_root: Path) -> dict[str, Any]:
    """Generate ``.github/workflows/dependabot-auto-merge.yml``.

    Returns a summary dict with ``file`` and ``action``.
    """
    wf_dir = project_root / ".github" / "workflows"
    wf_dir.mkdir(parents=True, exist_ok=True)
    target = wf_dir / "dependabot-auto-merge.yml"
    target.write_text(_DEPENDABOT_AUTO_MERGE, encoding="utf-8")
    return {"file": str(target.relative_to(project_root)), "action": "created"}


def generate_reusable_quality_workflow(project_root: Path) -> dict[str, Any]:
    """Generate ``.github/workflows/tapps-quality-reusable.yml``.

    Returns a summary dict with ``file`` and ``action``.
    """
    wf_dir = project_root / ".github" / "workflows"
    wf_dir.mkdir(parents=True, exist_ok=True)
    target = wf_dir / "tapps-quality-reusable.yml"
    target.write_text(_REUSABLE_QUALITY_WORKFLOW, encoding="utf-8")
    return {"file": str(target.relative_to(project_root)), "action": "created"}


def generate_all_ci_workflows(project_root: Path) -> dict[str, Any]:
    """Generate all GitHub Actions CI workflows.

    Convenience function that calls all individual workflow generators.

    Returns a summary dict with sub-results for each workflow.
    """
    results: dict[str, Any] = {}
    results["quality_workflow"] = generate_enhanced_ci_workflow(project_root)
    results["codeql_workflow"] = generate_codeql_workflow(project_root)
    results["copilot_setup_steps"] = generate_copilot_setup_steps(project_root)
    results["dependabot_auto_merge"] = generate_dependabot_auto_merge(project_root)
    results["reusable_quality_workflow"] = generate_reusable_quality_workflow(project_root)
    results["total_workflows"] = 5
    results["success"] = True
    return results
