"""Generator logic for docs/SPRINT_BOARD.md from a Linear open-issue snapshot.

Source of truth is Linear (TappsCodingAgents / TappsMCP Platform), not this
module or its output. See docs/TAPPS_BACKLOG_PLAN.md for why a hand-maintained
board drifted before. CLI entry point: scripts/gen-sprint-board.py.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docs" / "SPRINT_BOARD.md"
SNAPSHOT_DIR = REPO_ROOT / ".tapps-mcp-cache" / "linear-snapshots"
PRIORITY_ORDER = ["Urgent", "High", "Medium", "Low"]
PROJECT_URL = "https://linear.app/tappscodingagents/project/tappsmcp-platform-105f94bfc199"
MAX_STAMP_AGE_DAYS = 30
_STAMP_PATTERN = re.compile(r"Generated:\s*(\d{4}-\d{2}-\d{2})")


@dataclass(frozen=True)
class Issue:
    """One open Linear issue relevant to the sprint board."""

    id: str
    title: str
    priority: str
    status: str
    parent_id: str | None
    url: str

    @classmethod
    def from_dict(cls, raw: dict[str, Any]) -> Issue:
        priority_field = raw.get("priority") or {}
        priority = priority_field.get("name") or "No priority"
        return cls(
            id=raw["id"],
            title=raw["title"],
            priority=priority,
            status=raw.get("status", ""),
            parent_id=raw.get("parentId"),
            url=raw["url"],
        )


def _priority_rank(priority: str) -> int:
    try:
        return PRIORITY_ORDER.index(priority)
    except ValueError:
        return len(PRIORITY_ORDER)


def _issue_sort_key(issue: Issue) -> tuple[int, str]:
    return (_priority_rank(issue.priority), issue.id)


def find_default_input() -> Path:
    """Return the newest snapshot file under .tapps-mcp-cache/linear-snapshots/."""
    if not SNAPSHOT_DIR.is_dir():
        raise FileNotFoundError(f"No --input given and snapshot dir does not exist: {SNAPSHOT_DIR}")
    candidates = sorted(SNAPSHOT_DIR.glob("*.json"), key=lambda p: p.stat().st_mtime)
    if not candidates:
        raise FileNotFoundError(
            f"No --input given and no snapshot files found under {SNAPSHOT_DIR}"
        )
    return candidates[-1]


def load_issues(input_path: Path) -> list[Issue]:
    """Load issues from a Linear snapshot JSON file."""
    data = json.loads(input_path.read_text(encoding="utf-8"))
    return [Issue.from_dict(raw) for raw in data["issues"]]


def _priority_counts(issues: list[Issue]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for issue in issues:
        counts[issue.priority] = counts.get(issue.priority, 0) + 1
    return counts


def _counts_summary(issues: list[Issue]) -> str:
    counts = _priority_counts(issues)
    parts = [f"{counts[p]} {p}" for p in PRIORITY_ORDER if counts.get(p)]
    return f"{len(issues)} open ({', '.join(parts)})"


def _group_by_parent(issues: list[Issue]) -> tuple[list[Issue], dict[str, list[Issue]]]:
    """Split issues into top-level items and a parent-id -> sorted children map."""
    by_id = {issue.id: issue for issue in issues}
    children: dict[str, list[Issue]] = {}
    top_level: list[Issue] = []
    for issue in issues:
        if issue.parent_id and issue.parent_id in by_id:
            children.setdefault(issue.parent_id, []).append(issue)
        else:
            top_level.append(issue)

    top_level.sort(key=_issue_sort_key)
    for child_list in children.values():
        child_list.sort(key=_issue_sort_key)
    return top_level, children


def _render_header(issues: list[Issue], generated: date) -> str:
    return (
        "<!-- GENERATED by scripts/gen-sprint-board.py — do not hand-edit.\n"
        "     Source of truth: Linear (TappsCodingAgents / TappsMCP Platform).\n"
        f"     Generated: {generated.isoformat()} · {_counts_summary(issues)} -->\n"
        "\n"
        "# TappsMCP Platform — Sprint Board\n"
        "\n"
        f"**Project:** [TappsMCP Platform]({PROJECT_URL})  \n"
        "**Team:** TappsCodingAgents (TAP)  \n"
        f"**Generated:** {generated.isoformat()}  \n"
        f"**Open issues:** {_counts_summary(issues)}\n"
        "\n"
        "> Regenerate with `python3 scripts/gen-sprint-board.py` after pulling a fresh "
        "Linear snapshot. Do not hand-edit — see docs/TAPPS_BACKLOG_PLAN.md.\n"
        "\n"
        "---"
    )


def _render_issue_line(issue: Issue, *, indent: str = "", with_priority: bool = False) -> str:
    suffix = f"_({issue.priority}, {issue.status})_" if with_priority else f"_({issue.status})_"
    return f"{indent}- [{issue.id}]({issue.url}) — {issue.title} {suffix}"


def _render_priority_sections(
    top_level: list[Issue], children: dict[str, list[Issue]]
) -> list[str]:
    lines: list[str] = []
    current_priority: str | None = None
    for issue in top_level:
        if issue.priority != current_priority:
            current_priority = issue.priority
            lines.append(f"## {current_priority}")
            lines.append("")
        lines.append(_render_issue_line(issue))
        for child in children.get(issue.id, []):
            lines.append(_render_issue_line(child, indent="  ", with_priority=True))
        lines.append("")
    return lines


def render(issues: list[Issue], generated: date) -> str:
    """Render the full SPRINT_BOARD.md content."""
    top_level, children = _group_by_parent(issues)
    lines = [_render_header(issues, generated), ""]
    lines.extend(_render_priority_sections(top_level, children))
    return "\n".join(lines).rstrip() + "\n"


def strip_generated_date(content: str) -> str:
    """Drop the volatile 'Generated: YYYY-MM-DD' stamp lines for --check comparisons."""
    return "\n".join(line for line in content.splitlines() if "Generated:" not in line)


def resolve_input_path(explicit: Path | None) -> Path:
    """Return the snapshot path to use: the explicit path, or the newest default."""
    return explicit if explicit is not None else find_default_input()


def is_fresh(content: str, existing: str) -> bool:
    """True when regenerated `content` matches `existing`, ignoring the date stamp."""
    return strip_generated_date(existing) == strip_generated_date(content)


def parse_generated_date(content: str) -> date:
    """Extract the `Generated: YYYY-MM-DD` stamp from a rendered board's header.

    Raises ValueError if no stamp is found — a board without a parseable
    stamp cannot be aged, so callers should treat that as a hard failure
    rather than silently skipping the freshness check.
    """
    match = _STAMP_PATTERN.search(content)
    if not match:
        raise ValueError("no 'Generated: YYYY-MM-DD' stamp found in content")
    return date.fromisoformat(match.group(1))


def stamp_age_days(content: str, today: date) -> int:
    """Return how many days old the content's generated stamp is, as of `today`."""
    return (today - parse_generated_date(content)).days


def is_stamp_fresh(content: str, today: date, max_age_days: int = MAX_STAMP_AGE_DAYS) -> bool:
    """True when the content's generated stamp is within `max_age_days` of `today`."""
    return stamp_age_days(content, today) <= max_age_days
