"""GitHub Actions CI workflow generators.

Generates the single CI workflow TappsMCP installs into consumer projects:
``codeql-analysis.yml``. Everything else (lint, tests, build, quality gate)
runs locally via the TappsMCP pipeline — we intentionally do not push that
work into GitHub Actions.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pathlib import Path


# ---------------------------------------------------------------------------
# CodeQL Scanning Workflow
# ---------------------------------------------------------------------------

_CODEQL_WORKFLOW = """\
# .github/workflows/codeql-analysis.yml
# Generated by TappsMCP tapps_init — edit as needed
name: CodeQL Analysis

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "30 6 * * 1"  # Monday 6:30 UTC

permissions:
  security-events: write
  contents: read

concurrency:
  group: codeql-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        language: [python]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: +security-extended

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"
"""

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_codeql_workflow(project_root: Path) -> dict[str, Any]:
    """Generate ``.github/workflows/codeql-analysis.yml``.

    Returns a summary dict with ``file`` and ``action``.
    """
    wf_dir = project_root / ".github" / "workflows"
    wf_dir.mkdir(parents=True, exist_ok=True)
    target = wf_dir / "codeql-analysis.yml"
    target.write_text(_CODEQL_WORKFLOW, encoding="utf-8")
    return {"file": str(target.relative_to(project_root)), "action": "created"}


def generate_all_ci_workflows(project_root: Path) -> dict[str, Any]:
    """Generate all GitHub Actions CI workflows.

    Emits only ``codeql-analysis.yml``. All other quality work runs locally
    via the TappsMCP pipeline rather than in GitHub Actions.
    """
    results: dict[str, Any] = {}
    results["codeql_workflow"] = generate_codeql_workflow(project_root)
    results["total_workflows"] = 1
    results["success"] = True
    return results
