"""GitHub governance and security configuration generators.

Epic 22: Generate CODEOWNERS template, SECURITY.md, ruleset setup scripts,
and a post-init setup guide for configurations that can only be done via
API or UI.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pathlib import Path


# ---------------------------------------------------------------------------
# SECURITY.md
# ---------------------------------------------------------------------------

_SECURITY_POLICY = """\
# Security Policy

## Supported Versions

| Version | Supported |
|---------|-----------|
| latest  | Yes       |

## Reporting a Vulnerability

If you discover a security vulnerability in this project, please report it
responsibly:

1. **Do NOT open a public issue.** Security vulnerabilities should be reported
   privately.
2. Use [GitHub's private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability)
   to submit your report.
3. Include:
   - A description of the vulnerability
   - Steps to reproduce
   - Potential impact
   - Suggested fix (if any)

## Response Timeline

- **Acknowledgment:** Within 48 hours of report
- **Assessment:** Within 1 week
- **Fix or mitigation:** Within 2 weeks for critical issues

## Security Measures

This project uses automated security scanning:

- **Bandit** — static analysis for common security issues in Python
- **Secret scanning** — detection of hardcoded API keys, tokens, and passwords
- **pip-audit** — dependency vulnerability scanning against the PyPI advisory database
- **CodeQL** — GitHub's semantic code analysis engine
- **Dependabot** — automated dependency updates with grouped security patches

## Scope

This policy applies to the latest release and the main development branch.
Older versions receive security patches on a best-effort basis.
"""

# ---------------------------------------------------------------------------
# CODEOWNERS Template
# ---------------------------------------------------------------------------

_CODEOWNERS_TEMPLATE = """\
# CODEOWNERS — generated by TappsMCP tapps_init
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
#
# Each line is a file pattern followed by one or more owners.
# Order matters — later patterns take precedence.
# Replace placeholder owners (@your-team) with actual GitHub usernames or teams.

# Default owner for everything
*                           @your-team

# Security-sensitive files require security team review
**/security/**              @your-team
SECURITY.md                 @your-team
.github/workflows/**        @your-team

# Configuration files
pyproject.toml              @your-team
.tapps-mcp.yaml             @your-team

# CI/CD workflows
.github/workflows/**        @your-team

# Documentation
docs/**                     @your-team
AGENTS.md                   @your-team
CLAUDE.md                   @your-team
"""

# ---------------------------------------------------------------------------
# Ruleset Setup Script (bash)
# ---------------------------------------------------------------------------

_RULESET_SETUP_SH = """\
#!/usr/bin/env bash
# TappsMCP Repository Ruleset Setup Script
# Generated by TappsMCP tapps_init
#
# This script uses the GitHub CLI (gh) to configure repository rulesets.
# Rulesets replaced branch protection rules as the modern standard (GA 2025).
#
# Prerequisites:
#   - gh CLI installed and authenticated
#   - Admin access to the repository
#
# Usage:
#   chmod +x .github/scripts/setup-rulesets.sh
#   .github/scripts/setup-rulesets.sh

set -euo pipefail

REPO=$(gh repo view --json nameWithOwner -q '.nameWithOwner')
echo "Configuring rulesets for: $REPO"

# Create main branch protection ruleset
echo "Creating main branch protection ruleset..."
gh api \\
  --method POST \\
  "repos/$REPO/rulesets" \\
  -f name="Main Branch Protection" \\
  -f target=branch \\
  -f enforcement=active \\
  --input - <<'RULES_JSON'
{
  "conditions": {
    "ref_name": {
      "include": ["refs/heads/main", "refs/heads/master"],
      "exclude": []
    }
  },
  "rules": [
    {
      "type": "pull_request",
      "parameters": {
        "required_approving_review_count": 1,
        "dismiss_stale_reviews_on_push": true,
        "require_last_push_approval": false,
        "required_review_thread_resolution": true
      }
    },
    {
      "type": "required_status_checks",
      "parameters": {
        "strict_required_status_checks_policy": true,
        "required_status_checks": [
          {
            "context": "TappsMCP Quality Gate"
          }
        ]
      }
    },
    {
      "type": "required_linear_history"
    }
  ]
}
RULES_JSON

echo "Ruleset created successfully."
echo ""
echo "Next steps:"
echo "  1. Verify at: https://github.com/$REPO/settings/rules"
echo "  2. Adjust required reviewers count as needed"
echo "  3. Add additional status checks if you have other CI jobs"
"""

# ---------------------------------------------------------------------------
# Ruleset Setup Script (PowerShell)
# ---------------------------------------------------------------------------

_RULESET_SETUP_PS1 = """\
# TappsMCP Repository Ruleset Setup Script (PowerShell)
# Generated by TappsMCP tapps_init
#
# Prerequisites:
#   - gh CLI installed and authenticated
#   - Admin access to the repository
#
# Usage:
#   .\\setup-rulesets.ps1

$ErrorActionPreference = "Stop"

$Repo = gh repo view --json nameWithOwner -q '.nameWithOwner'
Write-Output "Configuring rulesets for: $Repo"

$RulesJson = @'
{
  "name": "Main Branch Protection",
  "target": "branch",
  "enforcement": "active",
  "conditions": {
    "ref_name": {
      "include": ["refs/heads/main", "refs/heads/master"],
      "exclude": []
    }
  },
  "rules": [
    {
      "type": "pull_request",
      "parameters": {
        "required_approving_review_count": 1,
        "dismiss_stale_reviews_on_push": true,
        "require_last_push_approval": false,
        "required_review_thread_resolution": true
      }
    },
    {
      "type": "required_status_checks",
      "parameters": {
        "strict_required_status_checks_policy": true,
        "required_status_checks": [
          {
            "context": "TappsMCP Quality Gate"
          }
        ]
      }
    },
    {
      "type": "required_linear_history"
    }
  ]
}
'@

$RulesJson | gh api --method POST "repos/$Repo/rulesets" --input -

Write-Output "Ruleset created successfully."
Write-Output ""
Write-Output "Next steps:"
Write-Output "  1. Verify at: https://github.com/$Repo/settings/rules"
Write-Output "  2. Adjust required reviewers count as needed"
Write-Output "  3. Add additional status checks if you have other CI jobs"
"""

# ---------------------------------------------------------------------------
# Post-Init Setup Guide
# ---------------------------------------------------------------------------

_SETUP_GUIDE = """\
# GitHub Setup Guide

> Generated by TappsMCP `tapps_init`. This guide covers configurations that
> cannot be set via repository files and require API or UI setup.

## 1. Repository Rulesets

Rulesets enforce branch protection, required reviews, and status checks.

### Option A: Run the setup script

```bash
# Bash (Linux/macOS)
chmod +x .github/scripts/setup-rulesets.sh
.github/scripts/setup-rulesets.sh

# PowerShell (Windows)
.\\github\\scripts\\setup-rulesets.ps1
```

### Option B: Manual setup

1. Go to **Settings > Rules > Rulesets**
2. Create a new ruleset targeting `main`/`master`
3. Enable:
   - Require pull request (1 reviewer minimum)
   - Require status checks: `TappsMCP Quality Gate`
   - Require linear history

## 2. Copilot MCP Server Registration

The Copilot coding agent needs TappsMCP registered as an MCP server:

1. Go to **Settings > Copilot > MCP Servers** (or use the API)
2. Add a new MCP server:
   - **Name:** `tapps-mcp`
   - **Command:** `tapps-mcp`
   - **Args:** `["serve"]`
   - **Env:** `{"TAPPS_MCP_PROJECT_ROOT": "."}`

Or via API:
```bash
gh api repos/{owner}/{repo}/copilot/mcp-servers \\
  --method POST \\
  -f name="tapps-mcp" \\
  -f command="tapps-mcp" \\
  -f 'args[]=serve'
```

## 3. Secret Scanning & Push Protection

Enable GitHub's built-in secret scanning:

1. Go to **Settings > Code security and analysis**
2. Enable:
   - **Secret scanning** — detects committed secrets
   - **Push protection** — blocks pushes containing secrets
   - **Validity checks** — verifies if detected secrets are active

## 4. Dependabot

The `dependabot.yml` configuration file has been generated. Additionally:

1. Go to **Settings > Code security and analysis**
2. Enable **Dependabot security updates** (auto-PRs for vulnerable dependencies)
3. Enable **Dependabot version updates** (uses the generated config)

## 5. Merge Queue (Optional)

For high-traffic repositories:

1. Go to **Settings > Rules > Rulesets**
2. Edit the main branch ruleset
3. Enable **Merge queue**:
   - Method: Squash
   - Min group size: 1
   - Max group size: 5
   - Wait time: 5 minutes

## 6. GitHub Projects (Optional)

For project management with issue tracking:

```bash
# Create a project board
gh project create --owner @me --title "Development Board"

# Add auto-add workflow for new issues
# (Configure in project Settings > Workflows)
```

## 7. Issue Types (Optional)

If your organization supports issue types:

```bash
# List available issue types
gh api orgs/{org}/issue-types

# The generated issue form templates use type: Bug, Feature, Task
# These map to organization-level issue types when available
```
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_security_policy(project_root: Path) -> dict[str, Any]:
    """Generate ``SECURITY.md`` in the project root.

    Returns a summary dict with ``file`` and ``action``.
    """
    target = project_root / "SECURITY.md"
    existed = target.exists()
    if existed:
        return {"file": "SECURITY.md", "action": "skipped", "reason": "already_exists"}
    target.write_text(_SECURITY_POLICY, encoding="utf-8")
    return {"file": "SECURITY.md", "action": "created"}


def generate_codeowners(project_root: Path) -> dict[str, Any]:
    """Generate ``.github/CODEOWNERS`` template.

    Returns a summary dict with ``file`` and ``action``.
    """
    github_dir = project_root / ".github"
    github_dir.mkdir(parents=True, exist_ok=True)
    target = github_dir / "CODEOWNERS"
    if target.exists():
        return {
            "file": str(target.relative_to(project_root)),
            "action": "skipped",
            "reason": "already_exists",
        }
    target.write_text(_CODEOWNERS_TEMPLATE, encoding="utf-8")
    return {"file": str(target.relative_to(project_root)), "action": "created"}


def generate_ruleset_scripts(project_root: Path) -> dict[str, Any]:
    """Generate ruleset setup scripts in ``.github/scripts/``.

    Creates both bash (``.sh``) and PowerShell (``.ps1``) scripts.

    Returns a summary dict with ``files`` and ``action``.
    """
    import stat

    scripts_dir = project_root / ".github" / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)

    files_written: list[str] = []

    sh_target = scripts_dir / "setup-rulesets.sh"
    sh_target.write_text(_RULESET_SETUP_SH, encoding="utf-8")
    sh_target.chmod(sh_target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)
    files_written.append(str(sh_target.relative_to(project_root)))

    ps1_target = scripts_dir / "setup-rulesets.ps1"
    ps1_target.write_text(_RULESET_SETUP_PS1, encoding="utf-8")
    files_written.append(str(ps1_target.relative_to(project_root)))

    return {"files": files_written, "action": "created", "count": len(files_written)}


def generate_setup_guide(project_root: Path) -> dict[str, Any]:
    """Generate ``docs/GITHUB_SETUP_GUIDE.md``.

    Returns a summary dict with ``file`` and ``action``.
    """
    docs_dir = project_root / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    target = docs_dir / "GITHUB_SETUP_GUIDE.md"
    target.write_text(_SETUP_GUIDE, encoding="utf-8")
    return {"file": str(target.relative_to(project_root)), "action": "created"}


def generate_all_governance(project_root: Path) -> dict[str, Any]:
    """Generate all governance and security configuration files.

    Convenience function that calls all individual generators.

    Returns a summary dict with sub-results.
    """
    results: dict[str, Any] = {}
    results["security_policy"] = generate_security_policy(project_root)
    results["codeowners"] = generate_codeowners(project_root)
    results["ruleset_scripts"] = generate_ruleset_scripts(project_root)
    results["setup_guide"] = generate_setup_guide(project_root)

    total_files = (
        1  # SECURITY.md
        + 1  # CODEOWNERS
        + results["ruleset_scripts"]["count"]
        + 1  # setup guide
    )
    results["total_files"] = total_files
    results["success"] = True
    return results
