"""Documentation automation generators for init/upgrade (Epic 86).

Creates documentation-focused agents, skills, and hooks for projects
that have DocsMCP configured. These complement the code-quality agents
already generated by the init pipeline.
"""

from __future__ import annotations

import importlib.resources
import re
import sys
from pathlib import Path
from typing import Any

import structlog

logger: structlog.stdlib.BoundLogger = structlog.get_logger()

_NLT_DOCS = "mcp__nlt-project-docs__"

# ---------------------------------------------------------------------------
# Package-data loaders (CLAUDE_DOC_AGENTS / CLAUDE_DOCS_SKILLS bodies)
# ---------------------------------------------------------------------------
#
# Mirrors tapps_mcp.prompts.prompt_loader._read_resource (same sys.frozen
# PyInstaller fallback) and platform_skills.py's own copy of this helper --
# duplicated locally to keep this module self-contained. Every body below
# interpolates the fixed _NLT_DOCS prefix, never resolve_role_model, so the
# marker is a single {{docs_prefix}} substitution rather than the
# {{model:role}} one CLAUDE_SKILLS uses.
_DOC_ASSET_PACKAGE = "tapps_mcp.pipeline"
_DOC_AGENT_ASSET_SUBDIR = "assets/claude_doc_agents"
_DOCS_SKILL_ASSET_SUBDIR = "assets/claude_docs_skills"
_DOCS_PREFIX_MARKER_RE = re.compile(r"\{\{docs_prefix\}\}")


def _read_doc_asset(subdir: str, file_name: str) -> str:
    if getattr(sys, "frozen", False):
        return (Path(__file__).parent / subdir / file_name).read_text(encoding="utf-8")
    ref = importlib.resources.files(_DOC_ASSET_PACKAGE).joinpath(f"{subdir}/{file_name}")
    return ref.read_text(encoding="utf-8")


def _load_claude_doc_agent(file_name: str) -> str:
    raw = _read_doc_asset(_DOC_AGENT_ASSET_SUBDIR, file_name)
    return _DOCS_PREFIX_MARKER_RE.sub(_NLT_DOCS, raw)


def _load_claude_docs_skill(skill_name: str) -> str:
    raw = _read_doc_asset(_DOCS_SKILL_ASSET_SUBDIR, f"{skill_name}.md")
    return _DOCS_PREFIX_MARKER_RE.sub(_NLT_DOCS, raw)


# ---------------------------------------------------------------------------
# Doc agent templates
# ---------------------------------------------------------------------------

CLAUDE_DOC_AGENTS: dict[str, str] = {
    "tapps-docs-reviewer.md": _load_claude_doc_agent("tapps-docs-reviewer.md"),
    "tapps-docs-validator.md": _load_claude_doc_agent("tapps-docs-validator.md"),
}

CURSOR_DOC_AGENTS: dict[str, str] = {
    "tapps-docs-reviewer.md": """\
---
name: tapps-docs-reviewer
description: >-
  Review documentation quality using DocsMCP validation tools. Checks drift,
  freshness, completeness, links, and Diataxis balance.
tools: Read, Glob, Grep, Write, Edit
model: claude-sonnet-5
maxTurns: 20
mcp_tools:
  - docs_check_drift
  - docs_check_freshness
  - docs_check_completeness
  - docs_check_links
  - docs_check_diataxis
---

You are a DocsMCP documentation reviewer. When invoked:

1. Call `docs_check_drift` on nlt-project-docs to find docs out of sync with code
2. Call `docs_check_freshness` to identify stale documentation
3. Call `docs_check_completeness` for a documentation health score
4. Call `docs_check_links` to find broken internal links
5. Call `docs_check_diataxis` for content balance analysis
6. Summarize findings by severity and recommend specific fixes

Focus on actionable feedback. Prioritize drift and broken links over style issues.
""",
    "tapps-docs-validator.md": """\
---
name: tapps-docs-validator
description: >-
  Run pre-completion documentation validation on changed markdown files.
  Checks freshness, links, and drift before declaring work done.
tools: Read, Glob, Grep
model: claude-haiku-4-5-20251001
maxTurns: 10
mcp_tools:
  - docs_check_links
  - docs_check_freshness
  - docs_check_drift
---

You are a lightweight documentation validator. When invoked:

1. Identify which markdown files were recently changed
2. Call `docs_check_links` on changed files
3. Call `docs_check_freshness` to verify nothing is stale
4. Call `docs_check_drift` on the project
5. Report pass/fail with brief explanation

Be concise. Only flag actual problems, not stylistic preferences.
""",
}


# ---------------------------------------------------------------------------
# Doc skill templates (Claude Code — nlt-project-docs MCP prefix)
# ---------------------------------------------------------------------------
#
# Each body lives as package data under assets/claude_docs_skills/, with a
# {{docs_prefix}} marker everywhere the body previously f-string-interpolated
# _NLT_DOCS, resolved by _load_claude_docs_skill() at load time.

CLAUDE_DOCS_SKILLS: dict[str, str] = {
    "tapps-docs-refresh": _load_claude_docs_skill("tapps-docs-refresh"),
    "tapps-docs-bootstrap": _load_claude_docs_skill("tapps-docs-bootstrap"),
    "tapps-docs-finish-task": _load_claude_docs_skill("tapps-docs-finish-task"),
    "tapps-docs-report": _load_claude_docs_skill("tapps-docs-report"),
    "tapps-docs-validate": _load_claude_docs_skill("tapps-docs-validate"),
    "tapps-docs-generate": _load_claude_docs_skill("tapps-docs-generate"),
}

# Backward-compatible alias (tests import DOCS_SKILLS)
DOCS_SKILLS: dict[str, str] = CLAUDE_DOCS_SKILLS

CURSOR_DOCS_SKILLS: dict[str, str] = {
    "tapps-docs-refresh": """\
---
name: tapps-docs-refresh
description: >-
  Full documentation refresh workflow (cross-refs, API, diagrams, validation).
  Use when refreshing project docs, auditing doc health, or pre-release doc pass.
mcp_tools:
  - docs_session_start
  - docs_check_cross_refs
  - docs_check_links
  - docs_generate_doc_index
  - docs_generate_purpose
  - docs_generate_onboarding
  - docs_generate_llms_txt
  - docs_generate_api
  - docs_generate_architecture
  - docs_generate_interactive_diagrams
  - docs_check_completeness
  - docs_check_freshness
  - docs_check_drift
  - docs_check_diataxis
  - docs_check_style
---

Run phases from `docs/tutorials/05-docs-refresh-workflow.md`: navigation → narrative → API/diagrams → verification (completeness ≥ 98, cross-refs ≥ 90) → optional style pass. Exclude `docs/archive/**`.
""",
    "tapps-docs-bootstrap": """\
---
name: tapps-docs-bootstrap
description: >-
  Bootstrap README, CONTRIBUTING, onboarding for new projects. Use when
  creating a README, onboarding guide, or initial doc scaffold.
mcp_tools:
  - docs_session_start
  - docs_module_map
  - docs_generate_readme
  - docs_generate_contributing
  - docs_generate_onboarding
  - docs_check_completeness
---

1. `docs_session_start` → `docs_module_map` → `docs_generate_readme(merge=true)` → `docs_generate_contributing` → `docs_generate_onboarding` → `docs_check_completeness` (target ≥ 80).
""",
    "tapps-docs-finish-task": """\
---
name: tapps-docs-finish-task
description: >-
  Doc-work finish bundle: drift, links, cross-refs, completeness, optional
  release gate. Use when documentation edits are complete before merge/release.
mcp_tools:
  - docs_check_drift
  - docs_check_links
  - docs_check_cross_refs
  - docs_check_completeness
  - docs_release_gate
  - tapps_checklist
---

Run drift → links → cross_refs → completeness; add `docs_release_gate` for releases; finish with `tapps_checklist(task_type=documentation)`.
""",
    "tapps-docs-report": """\
---
name: tapps-docs-report
description: >-
  Documentation quality report via project scan, completeness, Diataxis.
  Use when you need a doc health dashboard.
mcp_tools:
  - docs_project_scan
  - docs_check_completeness
  - docs_check_diataxis
---

Run scan + completeness + Diataxis; present summary table.
""",
    "tapps-docs-validate": """\
---
name: tapps-docs-validate
description: >-
  Lighter doc validation: drift, freshness, links, Diataxis. Use before
  merge when you do not need the full finish-task bundle.
mcp_tools:
  - docs_check_drift
  - docs_check_freshness
  - docs_check_links
  - docs_check_diataxis
---

Run all four checks; report pass/fail.
""",
    "tapps-docs-generate": """\
---
name: tapps-docs-generate
description: >-
  Quick generate README, llms.txt, changelog, runbook, postmortem. Use for
  minimal generation; prefer tapps-docs-bootstrap for new projects.
mcp_tools:
  - docs_generate_readme
  - docs_generate_llms_txt
  - docs_generate_changelog
  - docs_generate_runbook
  - docs_generate_postmortem
---

Generate requested artifacts; summarize files written.
""",
}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def detect_docsmcp(project_root: Path) -> bool:
    """Return True when DocsMCP is importable or declared in project deps.

    Mirrors the detection used by ``tapps_init`` so ``tapps_upgrade`` can refresh
    doc automation under the same condition. Checks importability of ``docs_mcp``
    first, then scans ``pyproject.toml`` / ``requirements*.txt`` for a docs-mcp dep.
    """
    try:
        import importlib

        importlib.import_module("docs_mcp")
    except ImportError:
        pass
    else:
        return True

    pyproject = project_root / "pyproject.toml"
    if pyproject.exists():
        try:
            content = pyproject.read_text(encoding="utf-8")
            if "docs-mcp" in content or "docs_mcp" in content:
                return True
        except OSError:
            pass

    for req_file in project_root.glob("requirements*.txt"):
        try:
            content = req_file.read_text(encoding="utf-8")
            if "docs-mcp" in content or "docs_mcp" in content:
                return True
        except OSError:
            pass

    return False


def generate_docs_agents(
    project_root: Path,
    platform: str,
    *,
    overwrite: bool = False,
) -> dict[str, Any]:
    """Generate documentation subagent definitions.

    Creates doc-focused agent files in ``.claude/agents/`` or
    ``.cursor/agents/``.

    Args:
        project_root: Project root directory.
        platform: ``"claude"`` or ``"cursor"``.
        overwrite: Whether to overwrite existing agent files.

    Returns:
        Summary dict with ``created``, ``updated``, ``skipped`` lists.
    """
    if platform == "claude":
        agents_dir = project_root / ".claude" / "agents"
        templates = CLAUDE_DOC_AGENTS
    elif platform == "cursor":
        agents_dir = project_root / ".cursor" / "agents"
        templates = CURSOR_DOC_AGENTS
    else:
        return {"created": [], "skipped": [], "error": f"Unknown platform: {platform}"}

    agents_dir.mkdir(parents=True, exist_ok=True)

    created: list[str] = []
    updated: list[str] = []
    skipped: list[str] = []
    for name, content in templates.items():
        target = agents_dir / name
        if target.exists():
            if overwrite:
                target.write_text(content, encoding="utf-8")
                updated.append(name)
            else:
                skipped.append(name)
        else:
            target.write_text(content, encoding="utf-8")
            created.append(name)

    return {"created": created, "updated": updated, "skipped": skipped}


def generate_docs_skills(
    project_root: Path,
    platform: str,
    *,
    overwrite: bool = False,
    create: bool = True,
) -> dict[str, Any]:
    """Generate documentation skill definitions.

    Creates doc-focused skill directories with SKILL.md files in
    ``.claude/skills/`` or ``.cursor/skills/``. Each ``SKILL.md`` is routed
    through the same BEGIN/END managed-block marker as every other registry
    skill (:func:`~tapps_mcp.pipeline.skill_managed_block.install_or_refresh_skill`),
    so it carries the one-line upgrade-policy header instead of being
    written verbatim (TAP-6612).

    Args:
        project_root: Project root directory.
        platform: ``"claude"`` or ``"cursor"``.
        overwrite: Whether to refresh an existing ``SKILL.md``'s managed
            block. When ``False``, an existing file is left untouched.
        create: Whether to write a ``SKILL.md`` that does not yet exist.
            When ``False``, a missing skill is reported as ``skipped``
            instead of created. This is independent of ``overwrite`` — a
            pinned ``.claude/skills``/``.cursor/skills`` directory (TAP-7428)
            must block *both* refreshing an existing file and creating one
            that is missing, otherwise deleting a pinned skill just makes it
            reappear on the next upgrade.

    Returns:
        Summary dict with ``created``, ``updated``, ``skipped`` lists.
    """
    from tapps_mcp.pipeline.skill_managed_block import install_or_refresh_skill

    if platform == "claude":
        skills_dir = project_root / ".claude" / "skills"
        templates = CLAUDE_DOCS_SKILLS
    elif platform == "cursor":
        skills_dir = project_root / ".cursor" / "skills"
        templates = CURSOR_DOCS_SKILLS
    else:
        return {"created": [], "skipped": [], "error": f"Unknown platform: {platform}"}

    created: list[str] = []
    updated: list[str] = []
    skipped: list[str] = []
    for skill_name, content in templates.items():
        skill_dir = skills_dir / skill_name
        target = skill_dir / "SKILL.md"
        if target.exists():
            if overwrite:
                action = install_or_refresh_skill(target, content, skill_name)
                (skipped if action == "unchanged" else updated).append(skill_name)
            else:
                skipped.append(skill_name)
        elif create:
            skill_dir.mkdir(parents=True, exist_ok=True)
            install_or_refresh_skill(target, content, skill_name)
            created.append(skill_name)
        else:
            skipped.append(skill_name)

    return {"created": created, "updated": updated, "skipped": skipped}


def generate_docs_automation(
    project_root: Path,
    platform: str,
    *,
    overwrite: bool = False,
    skills_overwrite: bool | None = None,
    skills_pinned: bool = False,
) -> dict[str, Any]:
    """Generate all documentation automation files (agents + skills).

    Convenience function combining agent and skill generation.

    Args:
        project_root: Project root directory.
        platform: ``"claude"`` or ``"cursor"``.
        overwrite: Whether to overwrite existing agent files.
        skills_overwrite: Whether to overwrite existing skill files. Defaults
            to *overwrite* when omitted, so existing callers that pass a
            single ``overwrite`` flag keep applying it to both halves. Passed
            separately (TAP-7428) because the two halves answer to different
            ``upgrade_skip_files`` tokens: agents to ``claude_agents`` /
            ``cursor_agents``, skills to ``claude_skills`` / ``cursor_skills``.
        skills_pinned: When ``True``, the skills half is neither refreshed
            *nor created* — this is what makes ``upgrade_skip_files:
            ['.claude/skills']`` mean "do not write here" for a
            not-yet-existing skill too, not just an existing one
            (TAP-7428). It overrides ``skills_overwrite``/``overwrite`` for
            the skills half only; the agents half is unaffected.

    Returns:
        Summary dict with ``agents`` and ``skills`` sub-dicts.
    """
    agents_result = generate_docs_agents(project_root, platform, overwrite=overwrite)
    skills_result = generate_docs_skills(
        project_root,
        platform,
        overwrite=(
            False
            if skills_pinned
            else (overwrite if skills_overwrite is None else skills_overwrite)
        ),
        create=not skills_pinned,
    )

    return {
        "agents": agents_result,
        "skills": skills_result,
    }
