"""Documentation automation generators for init/upgrade (Epic 86).

Creates documentation-focused agents, skills, and hooks for projects
that have DocsMCP configured. These complement the code-quality agents
already generated by the init pipeline.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import structlog

logger: structlog.stdlib.BoundLogger = structlog.get_logger()


# ---------------------------------------------------------------------------
# Doc agent templates
# ---------------------------------------------------------------------------

CLAUDE_DOC_AGENTS: dict[str, str] = {
    "tapps-docs-reviewer.md": """\
---
name: tapps-docs-reviewer
description: >-
  Review documentation quality using DocsMCP validation tools. Checks drift,
  freshness, completeness, links, and Diataxis balance.
tools: Read, Glob, Grep, Write, Edit
model: claude-sonnet-4-6
maxTurns: 20
permissionMode: plan
memory: project
mcpServers:
  docs-mcp: {}
---

You are a DocsMCP documentation reviewer. When invoked:

1. Call `mcp__docs-mcp__docs_check_drift` to find docs that are out of sync with code
2. Call `mcp__docs-mcp__docs_check_freshness` to identify stale documentation
3. Call `mcp__docs-mcp__docs_check_completeness` for a documentation health score
4. Call `mcp__docs-mcp__docs_check_links` to find broken internal links
5. Call `mcp__docs-mcp__docs_check_diataxis` for content balance analysis
6. Summarize findings by severity and recommend specific fixes

Focus on actionable feedback. Prioritize drift and broken links over style issues.
""",
    "tapps-docs-validator.md": """\
---
name: tapps-docs-validator
description: >-
  Run pre-completion documentation validation on changed markdown files.
  Checks freshness, links, and drift before declaring work done.
tools: Read, Glob, Grep
model: claude-haiku-4-5-20251001
maxTurns: 10
permissionMode: plan
memory: project
mcpServers:
  docs-mcp: {}
---

You are a lightweight documentation validator. When invoked:

1. Identify which markdown files were recently changed
2. Call `mcp__docs-mcp__docs_check_links` on changed files
3. Call `mcp__docs-mcp__docs_check_freshness` to verify nothing is stale
4. Call `mcp__docs-mcp__docs_check_drift` on the project
5. Report pass/fail with brief explanation

Be concise. Only flag actual problems, not stylistic preferences.
""",
}

CURSOR_DOC_AGENTS: dict[str, str] = {
    "tapps-docs-reviewer.md": """\
---
name: tapps-docs-reviewer
description: >-
  Review documentation quality using DocsMCP validation tools. Checks drift,
  freshness, completeness, links, and Diataxis balance.
tools: Read, Glob, Grep, Write, Edit
model: claude-sonnet-4-6
maxTurns: 20
---

You are a DocsMCP documentation reviewer. When invoked:

1. Call `mcp__docs-mcp__docs_check_drift` to find docs that are out of sync with code
2. Call `mcp__docs-mcp__docs_check_freshness` to identify stale documentation
3. Call `mcp__docs-mcp__docs_check_completeness` for a documentation health score
4. Call `mcp__docs-mcp__docs_check_links` to find broken internal links
5. Call `mcp__docs-mcp__docs_check_diataxis` for content balance analysis
6. Summarize findings by severity and recommend specific fixes

Focus on actionable feedback. Prioritize drift and broken links over style issues.
""",
    "tapps-docs-validator.md": """\
---
name: tapps-docs-validator
description: >-
  Run pre-completion documentation validation on changed markdown files.
  Checks freshness, links, and drift before declaring work done.
tools: Read, Glob, Grep
model: claude-haiku-4-5-20251001
maxTurns: 10
---

You are a lightweight documentation validator. When invoked:

1. Identify which markdown files were recently changed
2. Call `mcp__docs-mcp__docs_check_links` on changed files
3. Call `mcp__docs-mcp__docs_check_freshness` to verify nothing is stale
4. Call `mcp__docs-mcp__docs_check_drift` on the project
5. Report pass/fail with brief explanation

Be concise. Only flag actual problems, not stylistic preferences.
""",
}


# ---------------------------------------------------------------------------
# Doc skill templates
# ---------------------------------------------------------------------------

_DOCS_REPORT_SKILL = """\
---
name: tapps-docs-report
description: >-
  Generate a documentation quality report. Runs project scan, completeness
  check, and Diataxis balance analysis.
allowed-tools: >-
  mcp__docs-mcp__docs_project_scan
  mcp__docs-mcp__docs_check_completeness
  mcp__docs-mcp__docs_check_diataxis
---

Run a comprehensive documentation quality report:

1. Call `mcp__docs-mcp__docs_project_scan` to inventory all documentation
2. Call `mcp__docs-mcp__docs_check_completeness` for a health score
3. Call `mcp__docs-mcp__docs_check_diataxis` for content balance analysis
4. Present a summary table with scores and recommendations
"""

_DOCS_VALIDATE_SKILL = """\
---
name: tapps-docs-validate
description: >-
  Validate documentation quality. Checks drift, freshness, links, and
  Diataxis balance across the project.
allowed-tools: >-
  mcp__docs-mcp__docs_check_drift
  mcp__docs-mcp__docs_check_freshness
  mcp__docs-mcp__docs_check_links
  mcp__docs-mcp__docs_check_diataxis
---

Validate documentation quality across the project:

1. Call `mcp__docs-mcp__docs_check_drift` to find docs out of sync with code
2. Call `mcp__docs-mcp__docs_check_freshness` to identify stale docs
3. Call `mcp__docs-mcp__docs_check_links` to find broken links
4. Call `mcp__docs-mcp__docs_check_diataxis` for content balance
5. Present pass/fail results with specific fixes needed
"""

_DOCS_GENERATE_SKILL = """\
---
name: tapps-docs-generate
description: >-
  Generate documentation files. Creates README, llms.txt, and changelog
  from project analysis.
allowed-tools: >-
  mcp__docs-mcp__docs_generate_readme
  mcp__docs-mcp__docs_generate_llms_txt
  mcp__docs-mcp__docs_generate_changelog
---

Generate documentation for the project:

1. Call `mcp__docs-mcp__docs_generate_readme` to create or update README.md
2. Call `mcp__docs-mcp__docs_generate_llms_txt` to create llms.txt
3. Call `mcp__docs-mcp__docs_generate_changelog` if git tags are present
4. Present a summary of generated files
"""

DOCS_SKILLS: dict[str, str] = {
    "tapps-docs-report": _DOCS_REPORT_SKILL,
    "tapps-docs-validate": _DOCS_VALIDATE_SKILL,
    "tapps-docs-generate": _DOCS_GENERATE_SKILL,
}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_docs_agents(
    project_root: Path,
    platform: str,
    *,
    overwrite: bool = False,
) -> dict[str, Any]:
    """Generate documentation subagent definitions.

    Creates doc-focused agent files in ``.claude/agents/`` or
    ``.cursor/agents/``.

    Args:
        project_root: Project root directory.
        platform: ``"claude"`` or ``"cursor"``.
        overwrite: Whether to overwrite existing agent files.

    Returns:
        Summary dict with ``created``, ``updated``, ``skipped`` lists.
    """
    if platform == "claude":
        agents_dir = project_root / ".claude" / "agents"
        templates = CLAUDE_DOC_AGENTS
    elif platform == "cursor":
        agents_dir = project_root / ".cursor" / "agents"
        templates = CURSOR_DOC_AGENTS
    else:
        return {"created": [], "skipped": [], "error": f"Unknown platform: {platform}"}

    agents_dir.mkdir(parents=True, exist_ok=True)

    created: list[str] = []
    updated: list[str] = []
    skipped: list[str] = []
    for name, content in templates.items():
        target = agents_dir / name
        if target.exists():
            if overwrite:
                target.write_text(content, encoding="utf-8")
                updated.append(name)
            else:
                skipped.append(name)
        else:
            target.write_text(content, encoding="utf-8")
            created.append(name)

    return {"created": created, "updated": updated, "skipped": skipped}


def generate_docs_skills(
    project_root: Path,
    platform: str,
    *,
    overwrite: bool = False,
) -> dict[str, Any]:
    """Generate documentation skill definitions.

    Creates doc-focused skill directories with SKILL.md files in
    ``.claude/skills/`` or ``.cursor/skills/``.

    Args:
        project_root: Project root directory.
        platform: ``"claude"`` or ``"cursor"``.
        overwrite: Whether to overwrite existing skill files.

    Returns:
        Summary dict with ``created``, ``updated``, ``skipped`` lists.
    """
    if platform == "claude":
        skills_dir = project_root / ".claude" / "skills"
    elif platform == "cursor":
        skills_dir = project_root / ".cursor" / "skills"
    else:
        return {"created": [], "skipped": [], "error": f"Unknown platform: {platform}"}

    created: list[str] = []
    updated: list[str] = []
    skipped: list[str] = []
    for skill_name, content in DOCS_SKILLS.items():
        skill_dir = skills_dir / skill_name
        skill_dir.mkdir(parents=True, exist_ok=True)
        target = skill_dir / "SKILL.md"
        if target.exists():
            if overwrite:
                target.write_text(content, encoding="utf-8")
                updated.append(skill_name)
            else:
                skipped.append(skill_name)
        else:
            target.write_text(content, encoding="utf-8")
            created.append(skill_name)

    return {"created": created, "updated": updated, "skipped": skipped}


def generate_docs_automation(
    project_root: Path,
    platform: str,
    *,
    overwrite: bool = False,
) -> dict[str, Any]:
    """Generate all documentation automation files (agents + skills).

    Convenience function combining agent and skill generation.

    Args:
        project_root: Project root directory.
        platform: ``"claude"`` or ``"cursor"``.
        overwrite: Whether to overwrite existing files.

    Returns:
        Summary dict with ``agents`` and ``skills`` sub-dicts.
    """
    agents_result = generate_docs_agents(project_root, platform, overwrite=overwrite)
    skills_result = generate_docs_skills(project_root, platform, overwrite=overwrite)

    return {
        "agents": agents_result,
        "skills": skills_result,
    }
