"""Project-root scaffolded scripts placed by tapps_init and refreshed by tapps_upgrade.

TAP-6884: ``scripts/measure.py`` and ``scripts/gitfacts.sh`` are proven, hand-written
probe scripts (not templates generated by this codebase) that enforce a discipline
their authors were repeatedly bitten by skipping: an unvalidated probe result read as
a finding when it was actually looking in the wrong place. Both are ported verbatim
from their staged originals via :func:`tapps_mcp.pipeline.skill_asset_policy.write_project_script`
onto the comment-syntax-aware managed-block asset class shipped in TAP-6497/TAP-6884
(:mod:`tapps_mcp.pipeline.skill_asset_policy`) -- project edits outside the marker
survive every ``tapps_upgrade``.

One line was changed from the staged original, and only one:

``scripts/gitfacts.sh``'s ``usage()`` read its own usage block with a position-pinned
``sed -n '3,9p' "${BASH_SOURCE[0]}"``. Managed-block wrapping prepends a policy-header
line and a BEGIN-marker line ahead of the script body, shifting every body line down by
two -- so the position-pinned read would silently print the wrong two lines (the
shebang and the file's opening description line) instead of the ``# Usage:`` block.
Changed to a content-anchored ``sed -n '/^# Usage:/,/^# *$/p'`` instead, which finds
the same block regardless of how many lines precede it. ``scripts/measure.py`` needed
no change.

Known limitation, not fixed here because :mod:`skill_asset_policy` is shipped and
frozen (TAP-6884 scope): the managed-block header and BEGIN marker land *before* the
body's ``#!`` shebang line, so ``chmod +x`` does not make either script directly
executable via ``./scripts/measure.py`` -- the kernel's shebang lookup only honors byte
1 of the file. Both scripts still parse (``python -m py_compile`` /
``bash -n``) and run correctly when invoked with an explicit interpreter
(``python3 scripts/measure.py ...`` / ``bash scripts/gitfacts.sh ...``), which is how
every test in this program invokes them. Fixing shebang placement would require
:mod:`skill_asset_policy` itself to special-case a leading ``#!`` line, which is out of
this lane's scope -- filed as a follow-up rather than worked around.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from tapps_mcp.pipeline.skill_asset_policy import write_project_script

if TYPE_CHECKING:
    from pathlib import Path

MEASURE_PY_REL_PATH = "scripts/measure.py"
GITFACTS_SH_REL_PATH = "scripts/gitfacts.sh"

_MEASURE_SCRIPT_SKILL_NAME = "measure-script"
_GITFACTS_SCRIPT_SKILL_NAME = "gitfacts-script"

MEASURE_PY_BODY = r'''#!/usr/bin/env python3
"""Extract a metric from many JSON records, with the probe discipline enforced rather than remembered.

    scripts/measure.py --repo <path> --files '<glob>' --key clipped_fraction --expect 0.982345
    scripts/measure.py --repo <path> --files '<glob>' --key gate_state --expect failed --group 3

Why this exists
---------------
On 2026-09-01, nine ad-hoc probes across two sessions returned an empty or wrong result that
would have read as a finding. Not one was a careless mistake; each was a default being wrong:

* wrong nesting        - assumed auto_qa.checks, the data was at curation.auto_qa.metrics
* wrong repo           - a subprocess inherited a cwd that was not the repo being asked about
* glob too wide        - '*/*/manifest.json' swept template dirs that ship to nobody, and the
                         superset was reported as the set
* naming seam          - an exact-identifier grep found nothing because producer and consumer
                         spell the same thing differently

Every one returned EMPTY, and empty reads as "not there" when it means "I did not look where it is".

Two rules are enforced here so they cannot be skipped:

1. ``--expect`` is MANDATORY. You must name a value you already know is in the data. If the probe
   cannot find it, you get a diagnosis instead of results. This is the known-positive assertion.
2. The DENOMINATOR is always printed: files scanned, records found, distinct groups. A number
   without its population is not a measurement -- "16 lines", "16 shown heroes" and "89 candidate
   records" are three different answers to what sounds like one question.

Known limit, stated because it bit us: a known-positive assertion tests RECALL (can the probe find
the truth?) and never PRECISION (is it also finding things it should not?). A probe can hold a
green assertion while measuring a superset. That is what ``--group`` and the printed denominator
are for -- look at them before believing the count.
"""
from __future__ import annotations

import argparse
import glob as globlib
import json
import os
import sys


def walk(obj, key, path=""):
    """Yield (path, value) for every occurrence of `key`, at any depth."""
    if isinstance(obj, dict):
        for k, v in obj.items():
            here = f"{path}/{k}"
            if k == key:
                yield here, v
            # a list of {"metric": "<key>", "value": ...} records is the common shape
            if k == "metric" and v == key and "value" in obj:
                yield path, obj["value"]
            yield from walk(v, key, here)
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            yield from walk(v, key, f"{path}[{i}]")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True, help="repo root; all globs are relative to it")
    ap.add_argument("--files", required=True, help="glob, e.g. 'assets/**/manifest.json'")
    ap.add_argument("--key", required=True, help="metric/field name to extract")
    ap.add_argument("--expect", required=True,
                    help="a value you KNOW is present (the known-positive assertion)")
    ap.add_argument("--group", type=int, default=None,
                    help="path segment index to group by, e.g. 3 for .../merch-lines/<LINE>/...")
    ap.add_argument("--fail-only", action="store_true", help="only show records whose sibling ok is false")
    args = ap.parse_args()

    root = os.path.abspath(args.repo)
    if not os.path.isdir(os.path.join(root, ".git")) and not os.path.isdir(root):
        print(f"not a directory: {root}", file=sys.stderr)
        return 2

    paths = sorted(globlib.glob(os.path.join(root, args.files), recursive=True))
    rows: list[tuple[str, str, object]] = []
    parse_errors = 0
    for p in paths:
        try:
            with open(p, encoding="utf-8") as fh:
                doc = json.load(fh)
        except (OSError, json.JSONDecodeError):
            parse_errors += 1
            continue
        rel = os.path.relpath(p, root)
        for jpath, val in walk(doc, args.key):
            rows.append((rel, jpath, val))

    print(f"glob            : {args.files}")
    print(f"files matched   : {len(paths)}" + (f"  ({parse_errors} unparseable)" if parse_errors else ""))
    print(f"records found   : {len(rows)}   <-- this is your DENOMINATOR; is it the population your claim is about?")

    if not rows:
        print(f"\nPROBE FAILED: key '{args.key}' not found in any matched file.")
        if paths:
            with open(paths[0], encoding="utf-8") as fh:
                doc = json.load(fh)
            found = list(walk(doc, args.key))
            if found:
                print(f"  The key DOES exist in {os.path.relpath(paths[0], root)} at: {found[0][0]}")
                print("  Your glob matched the right files; something else dropped the rows.")
            else:
                print(f"  Not present in {os.path.relpath(paths[0], root)} either.")
                print("  Check: is the key spelled as the PRODUCER spells it? Is the glob the shipped path?")
        else:
            print("  The glob matched NO files. Empty here means 'I did not look where it is'.")
        return 1

    # ---- known-positive assertion, before any result is believed -------------
    def matches(v) -> bool:
        if str(v) == str(args.expect):
            return True
        try:
            return abs(float(v) - float(args.expect)) < 1e-6
        except (TypeError, ValueError):
            return False

    if not any(matches(v) for _, _, v in rows):
        print(f"\nPROBE INVALID: expected value {args.expect!r} not present among {len(rows)} records.")
        sample = sorted({str(v) for _, _, v in rows})[:8]
        print(f"  Sample of what WAS found: {sample}")
        print("  Do not use these results. Either the expectation is wrong or the probe is looking")
        print("  in the wrong place -- and an unvalidated probe's output is not evidence.")
        return 1

    print(f"assertion       : PASSED, {args.expect} present  (recall proven; precision is NOT)")

    groups: dict[str, list[object]] = {}
    for rel, _jpath, val in rows:
        gk = rel.split(os.sep)[args.group] if args.group is not None and len(rel.split(os.sep)) > args.group else rel
        groups.setdefault(gk, []).append(val)
    print(f"distinct groups : {len(groups)}")

    numeric = []
    for g, vals in sorted(groups.items()):
        nums = [v for v in vals if isinstance(v, (int, float)) and not isinstance(v, bool)]
        if nums:
            numeric.append((g, max(nums)))
        else:
            uniq = sorted({str(v) for v in vals})
            print(f"  {g:<42} {','.join(uniq)}")
    for g, mx in sorted(numeric, key=lambda x: -x[1]):
        print(f"  {g:<42} max={mx}")

    print("\nBefore quoting any count above: does 'distinct groups' name the population your")
    print("sentence is about? A superset reported as the set is a green assertion and a wrong claim.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

GITFACTS_SH_BODY = r"""#!/usr/bin/env bash
# The five git questions an orchestrator asks constantly, answered correctly once.
#
# Usage:
#   scripts/gitfacts.sh adds    <repo> <ref>        what this ref ADDS vs origin/main (three-dot)
#   scripts/gitfacts.sh landed  <repo> <ref>        is this ref's content already on origin/main?
#   scripts/gitfacts.sh content <repo> <string>     when did <string> enter/leave origin/main?
#   scripts/gitfacts.sh stale   <repo>              is this checkout behind origin/main?
#   scripts/gitfacts.sh sessions <repo>             live sessions sharing this working tree
#     (exits 0 whenever it successfully counts sessions, regardless of the count --
#      a caller doing `if gitfacts.sh sessions .; then` must see 0 in BOTH the safe
#      case (0 or 1 sessions) and the hazard case (2+); only a failure to determine
#      the count at all should exit non-zero)
#
# Every one of these was hand-rolled during the 2026-09-01 program and every one was
# got wrong at least once. The errors were not carelessness, they were the commands
# being subtly wrong by default:
#
#   * `git diff origin/main <ref>` (TWO dots) shows main's newer work as deletions when
#     the ref is behind. It reported 1298 files / 58k deletions for a branch that added
#     five. Three-dot is almost always what you meant.
#   * `git log -S` without an explicit ref searches the CHECKOUT's HEAD, which is routinely
#     stale. It returned "never on main" for content that was merged and then purged.
#   * A branch that is `ahead 1` may be unmerged work, OR work that landed by another
#     route, OR work that landed and was deliberately reverted. `rev-list --count` says 1
#     for all three. Only content comparison tells them apart -- and the third case is a
#     compliance hazard that presents as routine cleanup.
set -euo pipefail

usage() { sed -n '/^# Usage:/,/^# *$/p' "${BASH_SOURCE[0]}" >&2; exit 2; }

CMD=${1:-}; REPO=${2:-}
[ -n "$CMD" ] && [ -n "$REPO" ] || usage
[ -d "$REPO/.git" ] || git -C "$REPO" rev-parse --git-dir >/dev/null 2>&1 || {
  echo "not a git checkout: $REPO" >&2; exit 1; }

g() { git -C "$REPO" "$@"; }
g fetch origin --quiet 2>/dev/null || echo "warning: fetch failed; results may be stale" >&2

case "$CMD" in
  adds)
    REF=${3:?usage: adds <repo> <ref>}
    echo "# what $REF adds vs origin/main (three-dot; two-dot would show main's work as deletions)"
    g diff --stat "origin/main...$REF"
    ;;

  landed)
    REF=${3:?usage: landed <repo> <ref>}
    files=$(g diff --name-only "origin/main...$REF")
    [ -n "$files" ] || { echo "VERDICT: ref adds nothing vs origin/main"; exit 0; }
    missing=0; total=0
    while IFS= read -r f; do
      [ -n "$f" ] || continue
      total=$((total + 1))
      if g cat-file -e "origin/main:$f" 2>/dev/null &&
         g diff --quiet "origin/main" "$REF" -- "$f" 2>/dev/null; then
        printf '  identical on main : %s\n' "$f"
      else
        printf '  DIFFERS or absent : %s\n' "$f"; missing=$((missing + 1))
      fi
    done <<< "$files"
    echo
    if [ "$missing" -eq 0 ]; then
      echo "VERDICT: all $total file(s) already on origin/main -- ref is SUPERSEDED."
      echo "  Deleting it loses nothing. 'ahead 1' here was the squash-merge illusion."
    else
      echo "VERDICT: $missing of $total file(s) differ from origin/main."
      echo "  Do NOT assume this is unmerged work. Run:  gitfacts.sh content $REPO '<a distinctive string>'"
      echo "  If it landed and was later REVERTED, merging forward re-introduces what someone removed."
    fi
    ;;

  content)
    S=${3:?usage: content <repo> <string>}
    echo "# history of '$S' on origin/main (explicit ref: a bare -S searches the stale checkout HEAD)"
    out=$(g log origin/main --format='%h %ad %s' --date=short -S "$S" || true)
    if [ -z "$out" ]; then
      echo "  no commit on origin/main added or removed this string"
      echo "  NOTE: absence here is only meaningful if the string is spelled as the producer spells it."
      echo "        An exact-identifier search across a naming seam is a false-negative machine."
    else
      echo "$out"
      echo
      echo "  Read this newest-first. If the string was ADDED and later REMOVED, the removal is"
      echo "  probably deliberate and re-introducing it reverts someone's decision."
    fi
    ;;

  stale)
    local_head=$(g rev-parse --short HEAD)
    remote_head=$(g rev-parse --short origin/main)
    behind=$(g rev-list --count "HEAD..origin/main")
    ahead=$(g rev-list --count "origin/main..HEAD")
    echo "HEAD=$local_head  origin/main=$remote_head  ahead=$ahead  behind=$behind"
    flagged=$(g ls-files -v | grep '^[a-z]' || true)
    if [ -n "$flagged" ]; then
      echo "ASSUME-UNCHANGED FILES PRESENT -- 'git status' is blind to these:"
      echo "$flagged" | sed 's/^/  /'
    fi
    [ "$behind" -eq 0 ] && echo "VERDICT: current." || {
      echo "VERDICT: STALE by $behind commit(s). Any -S / grep / read here answers about old code."; }
    ;;

  sessions)
    n=0
    for p in $(pgrep -f 'native-binary/claude' 2>/dev/null || true); do
      d=$(readlink "/proc/$p/cwd" 2>/dev/null || true)
      [ "$d" = "$(cd "$REPO" && pwd)" ] && { echo "  pid $p"; n=$((n + 1)); }
    done
    echo "VERDICT: $n live session(s) share this working tree and its single git index."
    if [ "$n" -gt 1 ]; then
      echo "  Any 'git add -A' by any of them stages the others' work. Use per-session worktrees."
    fi
    ;;

  *) usage ;;
esac
"""


def generate_measure_script(project_root: Path, *, dry_run: bool = False) -> dict[str, Any]:
    """Install or refresh ``scripts/measure.py`` at the project root.

    Returns a summary dict with ``file`` and ``action`` (see
    :func:`tapps_mcp.pipeline.skill_asset_policy.write_project_script` for the
    ``AssetAction`` values).
    """
    action = write_project_script(
        project_root,
        MEASURE_PY_REL_PATH,
        MEASURE_PY_BODY,
        _MEASURE_SCRIPT_SKILL_NAME,
        dry_run=dry_run,
    )
    return {"file": MEASURE_PY_REL_PATH, "action": action}


def generate_gitfacts_script(project_root: Path, *, dry_run: bool = False) -> dict[str, Any]:
    """Install or refresh ``scripts/gitfacts.sh`` at the project root.

    Returns a summary dict with ``file`` and ``action`` (see
    :func:`tapps_mcp.pipeline.skill_asset_policy.write_project_script` for the
    ``AssetAction`` values).
    """
    action = write_project_script(
        project_root,
        GITFACTS_SH_REL_PATH,
        GITFACTS_SH_BODY,
        _GITFACTS_SCRIPT_SKILL_NAME,
        dry_run=dry_run,
    )
    return {"file": GITFACTS_SH_REL_PATH, "action": action}


__all__ = [
    "GITFACTS_SH_BODY",
    "GITFACTS_SH_REL_PATH",
    "MEASURE_PY_BODY",
    "MEASURE_PY_REL_PATH",
    "generate_gitfacts_script",
    "generate_measure_script",
]
